package com.cts.uam.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * AuditLog - records every login attempt and important UAM action.
 *
 * Stored in table: cts_audit_log
 *
 * An audit row is written for:
 * - LOGIN_SUCCESS : user logged in successfully
 * - LOGIN_FAILURE : wrong password entered
 * - ACCOUNT_LOCKED : account got locked after too many failures
 * - LOGOUT : user logged out
 * - USER_APPROVED : checker approved a new user
 * - USER_REJECTED : checker rejected a new user
 * - ROLE_APPROVED : checker approved a new role
 * - (and more event types for other UAM actions)
 *
 * Rows are never deleted - this is a permanent audit trail.
 */
@Entity
@Table(name = "cts_audit_log", indexes = {
        @Index(name = "idx_audit_username", columnList = "username"),
        @Index(name = "idx_audit_time", columnList = "event_time")
})
public class AuditLog {

    // Primary key - auto generated by DB
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Username of the person who triggered this event
    @Column(name = "username", nullable = false, length = 50)
    private String username;

    // Type of event - e.g. LOGIN_SUCCESS, USER_APPROVED, ROLE_REJECTED
    @Column(name = "event_type", nullable = false, length = 30)
    private String eventType;

    // IP address of the client (null for system-generated events)
    @Column(name = "ip_address", length = 45)
    private String ipAddress;

    // Browser/client info (null for system-generated events)
    @Column(name = "user_agent", length = 255)
    private String userAgent;

    // Extra detail about what happened (e.g. "User #5 approved by admin")
    @Column(name = "details", length = 500)
    private String details;

    // When this event happened - set automatically before INSERT
    @Column(name = "event_time", nullable = false)
    private LocalDateTime eventTime;

    // Runs automatically before INSERT - stamps the event time
    @PrePersist
    protected void onCreate() {
        eventTime = LocalDateTime.now();
    }

    // ── Constructors ──────────────────────────────────────────────────────

    // Empty constructor required by JPA
    public AuditLog() {
    }

    // Convenience constructor used by service classes to create audit rows
    public AuditLog(String username, String eventType, String ipAddress,
            String userAgent, String details) {
        this.username = username;
        this.eventType = eventType;
        this.ipAddress = ipAddress;
        this.userAgent = userAgent;
        this.details = details;
    }

    // ── Getters ───────────────────────────────────────────────────────────
    public Long getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getEventType() {
        return eventType;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public String getUserAgent() {
        return userAgent;
    }

    public String getDetails() {
        return details;
    }

    public LocalDateTime getEventTime() {
        return eventTime;
    }
}