package com.cts.uam.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Permission - one specific action that can be allowed or denied.
 *
 * Stored in table: cts_permissions
 *
 * Permissions are pre-seeded in the DB (not created by users).
 * Each permission belongs to a module (e.g. "OUTWARD", "UAM", "INWARD").
 *
 * Roles are assigned sets of permissions via the cts_role_permissions table.
 * Example permission: key="OUTWARD_BATCH_CREATE", module="OUTWARD"
 */
@Entity
@Table(name = "cts_permissions")
public class Permission {

    // Primary key - auto generated by DB
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Unique machine-readable key used in code (e.g. "OUTWARD_BATCH_SUBMIT")
    @Column(name = "permission_key", unique = true, nullable = false)
    private String permissionKey;

    // Human-readable name shown in the permission tree UI
    @Column(name = "display_name")
    private String displayName;

    // Which module this permission belongs to (e.g. "OUTWARD", "UAM", "INWARD")
    @Column(name = "module")
    private String module;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPermissionKey() {
        return permissionKey;
    }

    public void setPermissionKey(String permissionKey) {
        this.permissionKey = permissionKey;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }
}