package com.cts.uam.model;

import java.time.LocalDateTime;
import jakarta.persistence.*;

import com.cts.uam.enums.RoleStatus;

/**
 * Role - one named role in the system (e.g. MAKER, CHECKER, ADMIN).
 *
 * Stored in table: cts_roles
 *
 * Lifecycle:
 * 1. Maker creates role -> status = PENDING
 * 2. Checker approves -> status = ACTIVE (role can now be assigned to users)
 * 3. Checker rejects -> status = REJECTED (row stays in DB for audit)
 * 4. Admin can also deactivate an ACTIVE role -> status = INACTIVE
 *
 * Permissions for this role are stored in a separate table:
 * cts_role_permissions
 */
@Entity
@Table(name = "cts_roles")
public class Role {

    // Primary key - auto generated by DB
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Unique name for this role - uppercase + underscores only (e.g.
    // "OUTWARD_MAKER")
    @Column(name = "role_name", unique = true, nullable = false)
    private String roleName;

    // Short description of what this role is for
    @Column(name = "description")
    private String description;

    // Current lifecycle status - starts as PENDING when created by maker
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    private RoleStatus status = RoleStatus.PENDING;

    // Username of the maker who submitted this role for approval
    @Column(name = "created_by")
    private String createdBy;

    // When this role was first created in the system
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    // Reason why checker rejected this role (stored for audit)
    @Column(name = "rejected_reason", columnDefinition = "TEXT")
    private String rejectedReason;

    // Runs automatically before INSERT - sets the createdAt timestamp
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    // ── Derived (not persisted) ───────────────────────────────────

    // Returns true only if this role is approved and currently active
    public boolean isActive() {
        return status == RoleStatus.ACTIVE;
    }

    // ── Getters & Setters ─────────────────────────────────────────

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public RoleStatus getStatus() {
        return status;
    }

    public void setStatus(RoleStatus status) {
        this.status = status;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getRejectedReason() {
        return rejectedReason;
    }

    public void setRejectedReason(String rejectedReason) {
        this.rejectedReason = rejectedReason;
    }
}