package com.cts.uam.model;

import com.cts.uam.enums.UserStatus;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * User - represents one user account in the system.
 *
 * Stored in table: cts_users
 *
 * Lifecycle:
 * 1. Maker creates user -> status = PENDING
 * 2. Checker approves -> status = ACTIVE, temp password is set
 * 3. Checker rejects -> status = REJECTED (row stays in DB for audit)
 *
 * Security fields track failed login attempts and temporary lockouts.
 */
@Entity
@Table(name = "cts_users", indexes = {
        @Index(name = "idx_username", columnList = "username", unique = true)
})
public class User {

    // Primary key - auto generated by DB
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Login username - must be unique across all users
    @Column(name = "username", nullable = false, length = 50, unique = true)
    private String username;

    // BCrypt hashed password - never stored as plain text
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    // User's display name (full name)
    @Column(name = "full_name", nullable = false, length = 100)
    private String fullName;

    // Name of the role assigned to this user (for display)
    @Column(name = "role_label", length = 50)
    private String roleLabel;

    @Column(name = "email", length = 100)
    private String email;

    @Column(name = "mobile", length = 15)
    private String mobile;

    // Current lifecycle status of this account
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    private UserStatus status = UserStatus.PENDING;

    // FK reference to cts_roles table
    @Column(name = "role_id")
    private Long roleId;

    // Username of the maker who submitted this user for approval
    @Column(name = "requested_by", length = 50)
    private String requestedBy;

    // Reason why checker rejected this user (stored for audit)
    @Column(name = "rejected_reason", columnDefinition = "TEXT")
    private String rejectedReason;

    // ── Security ──────────────────────────────────────────────────

    // How many times login failed in a row - resets to 0 on success
    @Column(name = "failed_attempts")
    private int failedAttempts = 0;

    // If set, user cannot log in until this time has passed
    @Column(name = "locked_until")
    private LocalDateTime lockedUntil;

    // When the user last successfully logged in
    @Column(name = "last_login")
    private LocalDateTime lastLogin;

    // ── Audit ─────────────────────────────────────────────────────

    // When this row was first created - never changes after that
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    // Updated every time any field on this row changes
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Runs automatically before INSERT - sets both timestamps
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    // Runs automatically before UPDATE - refreshes updatedAt
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // ── Constructors ──────────────────────────────────────────────
    public User() {
    }

    // ── Derived methods (not persisted) ───────────────────────────

    // Returns true only if the account is fully approved and usable
    public boolean isActive() {
        return status == UserStatus.ACTIVE;
    }

    // Returns true if the account is locked by status OR by a timed lock
    public boolean isLocked() {
        if (status == UserStatus.LOCKED)
            return true;
        return lockedUntil != null && LocalDateTime.now().isBefore(lockedUntil);
    }

    // ── Getters & Setters ─────────────────────────────────────────

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String v) {
        this.username = v;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String v) {
        this.passwordHash = v;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String v) {
        this.fullName = v;
    }

    public String getRoleLabel() {
        return roleLabel;
    }

    public void setRoleLabel(String v) {
        this.roleLabel = v;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String v) {
        this.email = v;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String v) {
        this.mobile = v;
    }

    public UserStatus getStatus() {
        return status;
    }

    public void setStatus(UserStatus v) {
        this.status = v;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long v) {
        this.roleId = v;
    }

    public String getRequestedBy() {
        return requestedBy;
    }

    public void setRequestedBy(String v) {
        this.requestedBy = v;
    }

    public String getRejectedReason() {
        return rejectedReason;
    }

    public void setRejectedReason(String v) {
        this.rejectedReason = v;
    }

    public int getFailedAttempts() {
        return failedAttempts;
    }

    public void setFailedAttempts(int v) {
        this.failedAttempts = v;
    }

    public LocalDateTime getLockedUntil() {
        return lockedUntil;
    }

    public void setLockedUntil(LocalDateTime v) {
        this.lockedUntil = v;
    }

    public LocalDateTime getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(LocalDateTime v) {
        this.lastLogin = v;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

}